export type Variant = {
  id: number,
  sku: string,
  grams: number,
  price: number,
  title: string,
  weight: number,
  barcode: string,
  option1: string | null,
  option2: string | null,
  option3: string | null,
  taxable: boolean,
  position: number,
  created_at: Date,
  product_id: number,
  updated_at: Date,
  weight_unit: string,
  compare_at_price: number | null,
  inventory_policy: string,
  inventory_item_id: number,
  requires_shipping: boolean,
  inventory_quantity: number,
  fulfillment_service: string,
  inventory_management: string
}